# ETF symbols used in this project

symbols:
  - VOO
  - SPY
  - QQQ
  - VGT
  - VT
  - VXUS
  - BND
  - GLD
  - VEA
  - VWO
  - BNDX
  - ACWI
  - EFA
  - IEMG
  - EWJ
  - MCHI
  - INDA
  - EWG
  - EWU
  - EWZ

source:
  name: yahoo_finance
  start_date: "2015-01-01"