version: 2

seeds:
  - name: etf_prices_incremental
    description: "Temporary landing batch containing the newest daily ETF prices."

    columns:
      - name: symbol
        data_tests:
          - not_null

      - name: price_date
        data_tests:
          - not_null

      - name: adjusted_close
        data_tests:
          - not_null

      - name: volume
        data_tests:
          - not_null


models:
  - name: etf_prices_raw
    description: "Incremental Bronze Delta table containing historical and daily ETF prices."

    columns:
      - name: symbol
        data_tests:
          - not_null

      - name: price_date
        data_tests:
          - not_null

      - name: adjusted_close
        data_tests:
          - not_null

      - name: volume
        data_tests:
          - not_null